[package]
name = "ash_macros_compile_fail"
edition = "2024"
description = "Compile fail tests for ash_macros"
publish = false

[dependencies]
ash_macros = { path = "../" }

[dev-dependencies]
compile_fail_utils = { path = "../../tools/compile_fail_utils" }

[[test]]
name = "ui"
harness = false

[lints]
workspace = true
